[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "attenpy"
version = "0.2.1"
description = "SDK for AttenAPI"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.9.0",
    "pydantic>=2.0.0",
]
license = { text = "MIT" }
authors = [
  { name = "AttenTeam" }
]

[project.urls]
Homepage = "https://atten.win/"
Repository = "https://github.com/attensns/attenpy"

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-asyncio>=0.21.0",
]

[tool.setuptools.packages.find]
include = ["attenpy*"]

[dependency-groups]
dev = [
    "basedpyright>=1.40.1",
    "ruff>=0.16.8",
]

[tool.ruff]
target-version = "py313"
line-length = 100

[tool.ruff.lint]
select = ["E","F","W","I","UP","B","SIM"]
preview = true

[tool.ruff.format]
quote-style = "double"
indent-style = "space"


[tool.basedpyright]
pythonVersion = "3.13"
venvPath = "."
venv = ".venv"

include = ["attenpy"]
exclude = [
    "**/__pycache__",
    ".venv",
    "build",
    "dist",
]

typeCheckingMode = "strict"

reportUnusedCallResult = false
reportMissingTypeStubs = false
reportImplicitOverride = false
reportPrivateUsage = false
reportUnnecessaryCast = false
